Adds insertBefore and insertAfter functions
elo7/doc-amd pull request #23
Opened 2015-12-21 20:10 UTC by danielyudiushino

# Changelog
- Adds function `insertBefore` which inserts an element before each matched element
- Adds function `insertAfter` which inserts an element after each matched element

@leocwolter

2015-12-29 11:55 UTC, mottam commented on doc.js
> +					el.insertAdjacentHTML('beforebegin', this.els[0].outerHTML);
If the element has no parent this function throws an error. Suppose you wish to create the elements before inserting into the DOM tree. These elements will have no parent. You could work around it by inserting an element as a parent of `el` if `el` has no parent and remove it afterwards in order to make this work.

@mottam @erikatakahara

2015-12-29 11:58 UTC, mottam commented on README.md
> +	doc('#some-element').insertBefore("a") //Inserts the element with id some-element before each <a> element
You should add the example where you pass a doc element instead of a string as well.

@mottam @erikatakahara

2015-12-29 11:58 UTC, mottam commented on README.md
> +	doc('#some-element').insertAfter("a") //Inserts the element with id some-element after each <a> element
You should add the example where you pass a doc element instead of a string as well.

@mottam @erikatakahara

2016-05-23 18:01 UTC, AlineLee commented on doc.js
> +					el.insertAdjacentHTML('beforebegin', this.els[0].outerHTML);
As discussed privately with @erikatakahara, inserting before/after elements without parent won't be supported. It's still possible to create a complex structure of elements before inserting them into the DOM by creating a root for them, which is the most common use case.

@luiz

2016-11-07 21:10 UTC, tcelestino requested changes
Fix

2016-11-07 21:10 UTC, tcelestino commented on README.md
> +>>>>>>> f4eebc8... Adds insertBefore and insertAfter functions
Should remove this info about to merge

2016-11-21 18:25 UTC, luiz commented on README.md
> +>>>>>>> f4eebc8... Adds insertBefore and insertAfter functions
Done

2016-12-05 20:38 UTC, tcelestino commented
Como o `insertAdjacentHTML` só está implementado no > IE11, não seria o caso de fazer um polyfill para "suportar" os < IE11? 

Dando uma fuçada, achei essa [solução](https://gist.github.com/eligrey/1276030) bem interessante e podemos deixar apenas para contexto dos métodos.

2016-12-05 20:38 UTC, tcelestino reviewed
Sugestão para melhorias

2016-12-05 20:38 UTC, tcelestino commented on doc.js
> +				if(typeof elements == 'string'){
Que tal usar aqui o `===` e assim deixa padronizado como está em outros métodos?

@tcelestino

2016-12-05 20:38 UTC, tcelestino commented on doc.js
> +				if(typeof elements == 'string'){
Idem.

@tcelestino

2016-12-29 17:05 UTC, diegocesar commented on doc.js
> +				if(typeof elements == 'string'){
Done

2016-12-29 17:05 UTC, diegocesar commented on doc.js
> +				if(typeof elements == 'string'){
Done

2017-01-02 10:37 UTC, merged