[lenient-off] Fix error when trying to off an event that has not been registered
elo7/doc-amd pull request #41
Opened 2017-01-13 16:07 UTC by diegocesar

@FernandaBernardo @luiz

Depends on: https://github.com/elo7/events-amd/pull/4

2017-01-13 18:28 UTC, erikatakahara requested changes

2017-01-13 18:28 UTC, erikatakahara commented on test/docTest.js.html
> +          it("should not throw error when off'ing an event that was not registered yet", function() {
Does this test fail when the function off throw an error? If not, is it really needed?

2017-01-16 11:25 UTC, luiz commented on test/docTest.js.html
> +          it("should not throw error when off'ing an event that was not registered yet", function() {
Yes, it does fail. We TDD'ed it :)

2017-01-18 09:46 UTC, erikatakahara approved these changes

2017-01-18 10:02 UTC, merged