[watch-js] Adiciona watch nos arquivos JS
elo7/doc-amd pull request #62
Opened 2020-06-01 15:27 UTC by thiagocorbalan

Foi adicionar um watch no arquivo doc.js para ajudar no desenvolvimento.
Além disso foi removido todos os arquivos .sh e inseridos no package.json como scripts para rodar com npm.

## Requisítos
- node ^v11.3.0

### Como Testar
- [ ] baixar o repositório com essa branch `watch-js` e rodar `npm install`
- [ ] rodar `start:dev` para subir o _server_ e o _watch_
- [ ] rodar `npm run test` para gerar o report dos tests no terminal.

2020-06-01 17:20 UTC, luiz requested changes

2020-06-01 17:20 UTC, luiz commented on package.json
> +    "start:dev": "npm run dev-server & npm run watch:js",
Que tal usar o pacote [npm-run-all](https://www.npmjs.com/package/npm-run-all) ou o [concurrently](https://www.npmjs.com/package/concurrently) para isso? Assim você tem mais controle de parar os processos.

2020-06-01 17:20 UTC, luiz commented on package.json
> +    "dev-server": "http-server -p 8888 & sleep 3",
Precisa do `sleep 3`?

2020-06-01 17:20 UTC, luiz commented on package.json
> +    "test": "mocha-chrome --reporter spec 'http://localhost:8888/test/docTest.js.html'",
O `test` era um script bash porque dependia da subida do servidor de testes primeiro. Se for alterar isso, é necessário fazer com que o servidor suba de alguma outra forma; pode ser por um script aqui do `package.json` mesmo. E também é necessário alterar o arquivo `.travis.yml`, porque atualmente ele está configurado para chamar diretamente o script `test.sh`.

2020-06-01 17:37 UTC, thiagocorbalan commented on package.json
> +    "dev-server": "http-server -p 8888 & sleep 3",
Eu acho que não Sr. SAúde, na vdd eu tinha testado sem e funcionou também! Vou remover!

2020-06-01 17:40 UTC, thiagocorbalan commented on package.json
> +    "start:dev": "npm run dev-server & npm run watch:js",
Com certeza! Farei isso!

2020-06-01 19:08 UTC, luiz requested changes

2020-06-01 19:08 UTC, luiz commented on package.json
> +    "server": "http-server -p 8888 ",
Sobrou um espacinho aqui :sweat_smile:

2020-06-01 19:08 UTC, luiz commented on .travis.yml
> + - npm run server & npm run test
Acho que seria mais interessante ter um script no `package.json` para isso e já usando o npm-run-all, para facilitar tanto a manutenção quanto a execução local dos testes.

2020-06-01 20:27 UTC, luiz commented on package.json
> +    "start": "npm isntall && run-s -l build server",
Não seria melhor o `npm ci`?
```suggestion
    "start": "npm ci && run-s -l build server",
```

2020-06-01 20:27 UTC, luiz commented on README.md
> +|-|-|
Precisa dessas duas linhas? Parece que criou uma linha vazia na tabela final...

2020-06-01 20:27 UTC, luiz commented on README.md
> +| `npm run start:dev` | Run all it exists at the start script and run the watch script. |
```suggestion
| `npm run start:dev` | Run the start script and then the watch script. |
```

2020-06-01 20:27 UTC, luiz commented on README.md
> +| `npm run test` | Run test local. |
```suggestion
| `npm run test` | Run test locally. |
```

2020-06-01 20:27 UTC, luiz commented on README.md
> +| `npm run test:ci` | Run test with together server for to continuous integration. |
```suggestion
| `npm run test:ci` | Run the server and the tests. Useful for a quick local check and for CI environment.  |
```

2020-06-01 20:33 UTC, thiagocorbalan commented on package.json
> +    "start": "npm isntall && run-s -l build server",
:hammer_and_pick:

2020-06-01 20:36 UTC, thiagocorbalan commented on README.md
> +|-|-|
Na teoria precisa sim para poder criar tabela no markdown. =/ 
Mas podemos fazer sem tabela mesmo, e suar apenas lista não ordenada! O que acha? :thinking:

2020-06-01 20:37 UTC, thiagocorbalan commented on README.md
> +| `npm run start:dev` | Run all it exists at the start script and run the watch script. |
:hammer_and_pick:

2020-06-01 20:37 UTC, thiagocorbalan commented on README.md
> +| `npm run test` | Run test local. |
:hammer_and_pick:

2020-06-01 20:38 UTC, thiagocorbalan commented on README.md
> +| `npm run test:ci` | Run test with together server for to continuous integration. |
Desculpe mas é que o meu inglês não é muito bom :cry:

2020-06-01 22:06 UTC, luiz commented on README.md
> +|-|-|
Acho que tabela ainda é a melhor opção, é a mais semântica a meu ver. Pelo que entendi olhando a documentação do Markdown, a primeira linha é o cabeçalho da tabela. Sendo assim, que tal preenchê-la com texto? Tipo:
```suggestion
|Script|Description|
|-|-|
```

2020-06-02 12:41 UTC, thiagocorbalan commented on README.md
> +|-|-|
:hammer_and_pick:

2020-06-15 20:24 UTC, luiz approved these changes

2020-06-15 20:38 UTC, merged